# Generated by Django 3.0 on 2019-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobber',
            name='fire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
